### ISSUE TITLE
Replace file by folder

### ISSUE THREAD

**Issue by Tutt-J** [libou06/Projet_3#1]
Your structure is wrong, you must have :

- **src**
- **templates**
- **public**
Inside public : 
- _index.php_
- **css** with _style.css_ and _reset.css_ inside
- **js** with script.js inside
- _.htaccess_
- _robot.txt_
- _sitemap.xml_

Folder is represent by **font-weight** and file by _italic_.

Please create an issue name like "1_correct_structure_error" and resolve the problem.

When it's done please send me a pull request.

**Comment by libou06** [comment]
Coucou
J'ai fais les modifications que tu m'a demandé mais je ne sais pas comment t'envoyer une nouvelle pull request! De plus je ne comprends pas pourquoi mes fichiers src et templates que j'ai crée n'apparaissent pas dans mon nouveau commit sur github? Ils sont pourtant bien présent dans mon fichier sur mon desktop et quand je fais un git status, ça m'indique que je n'ai rien à commiter!

**Comment by Tutt-J** [comment]
Hi !

So this is the step : 

- Create an issue
- Create a branch (NEVER WORK ON MASTER)
- Resolve problems
- git add .
- git commit -m "Message"
- git push

When it's done, go to your github repository on your browser.
Click on "pull request" tab on your repository and "New pull request", then choose your branch (on compare). You can now click on "Create pull request". Let me a comment with identification and i will see this.

Please use english when you work on github (even if you don't speak english very well like me)

**Comment by libou06** [comment]
Hi
Ok I've tried to resolve the problem but when I create the folder "src" or "templates" on git, with "git mkdir", the forlder appaers in the big folder "P_3_Fukalla_Typhanie" but when I do "git add ." and "git status", it writen "nothing to commit, working tree clean". I don't understand why.. I'm working on a new branch "message" but it doesn't work..
And can you explain to me also why we need to speak in english on github, please?
Thanks :)
